### ISSUE TITLE
Looking for an example using XHR (like https://github.com/dmjio/miso/tree/master/examples/xhr)

### ISSUE THREAD

**Issue by alaendle** [tweag/ghc-wasm-miso-examples#15]
At the moment I'm just playing around with `miso` and the JS and WASM backends.

The JS backend is practically unusable as there is C code everywhere (e.g. `hashable` as a prominent example), while in the WASM backend `ghcjs-base` is unusable. So how do you use XHRs?

So basically I'm searching for a "translation" of https://github.com/dmjio/miso/tree/master/examples/xhr using WASI.

Maybe I missed some obvious solution; but maybe you could point me the right direction.

**Comment by amesgen** [comment]
One straightforward way to make this work on the WASM backend is to use the WASM JS FFI:
```haskell
foreign import javascript safe "const r = await fetch($1); return r.text();"
  js_fetch :: JSString -> IO JSString
```

I opened a PR adding the xhr Miso example to this repo, using this approach.

If you want your code to eg also work when compiling with non-cross GHC and using jsaddle-warp, you can use fetch or XMLHttpRequest via JSaddle, for example via ghcjs-dom, servant-jsaddle or servant-client-js.

---

Also, this topic recently came up in the Matrix GHC WASM room, in case you are interested: https://matrix.to/#/#haskell-wasm:matrix.terrorjack.com

**Comment by alaendle** [comment]
Thank you so much @amesgen ! You are the best! I actually thought I had tried that too - but I must have done something wrong! Thank you so much for pointing me in the right direction so quickly.
