### ISSUE TITLE
2048 stuck at "Game Won!"

### ISSUE THREAD

**Issue by turion** [tweag/ghc-wasm-miso-examples#19]
When I win the 2048 game, I get this screen:

![image](https://github.com/user-attachments/assets/5777da42-dc0e-4ecb-8f7a-42913bf5642a)

Now when I click "Keep going" and try to go on playing, the same screen comes again. So I effectively can't go on playing.

**Comment by amesgen** [comment]
Thanks! Turns out that this was a bug in the original https://github.com/ptigwe/hs2048, see #20 for details.
